// <auto-generated>
// Rewired Constants
// This list was generated on 4/28/2023 9:58:16 PM
// The list applies to only the Rewired Input Manager from which it was generated.
// If you use a different Rewired Input Manager, you will have to generate a new list.
// If you make changes to the exported items in the Rewired Input Manager, you will
// need to regenerate this list.
// </auto-generated>

namespace RewiredConsts {
    public static partial class Action {
        // Default
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Primary Horizontal")]
        public const int PHorizontal = 0;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Primary Vertical")]
        public const int PVertical = 1;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Secondary Horizontal")]
        public const int SHorizontal = 2;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Secondary Vertical")]
        public const int SVertical = 3;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Jump")]
        public const int Jump = 4;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Target")]
        public const int Target = 5;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Shoot")]
        public const int Shoot = 6;
        
        [Rewired.Dev.ActionIdFieldInfo(categoryName = "Default", friendlyName = "Switch")]
        public const int Switch = 8;
        
    }
    public static partial class Category {
        public const int Default = 0;
        
    }
    public static partial class Layout {
        public static partial class Joystick {
            public const int Default = 0;
            
            public const int TwoStick = 1;
            
        }
        public static partial class Keyboard {
            public const int Default = 0;
            
        }
        public static partial class Mouse {
            public const int Default = 0;
            
        }
        public static partial class CustomController {
            public const int Default = 0;
            
        }
    }
    public static partial class Player {
        [Rewired.Dev.PlayerIdFieldInfo(friendlyName = "System")]
        public const int System = 9999999;
        
    }
    public static partial class CustomController {
    }
    public static partial class LayoutManagerRuleSet {
    }
    public static partial class MapEnablerRuleSet {
    }
}
